Localized country list
spanastasia/INTITA pull request #79
Opened 2021-01-29 13:06 UTC by Stepan19897

2021-01-29 13:29 UTC, svitlana-korostelova commented on INTITA/JSONFiles/CountryService.swift
> +        return country
Maybe it would be better to rename, because it's array, not 1 country?

2021-01-29 13:50 UTC, svitlana-korostelova commented on INTITA/JSONFiles/CountryService.swift
> +    func getCountries() -> [CountryModel]? {
I suppose this model CountryService should have the private property: a dictionary of instances of CountryModel like this var dict : [String : String] = ["UA" : "*istanceNameOfCountryModel*"], wherefrom you can get 1 country throw func getCountries() like this: var country = dict["UA"]. To get localized in switch: dict["UA"]?.titleUA

2021-02-02 17:49 UTC, oleksiikolomiietssnapp requested changes

2021-02-02 17:49 UTC, oleksiikolomiietssnapp commented on INTITATests/CountryList.swift
> +        XCTAssertEqual(geocode.localizedCountry(locale: Locale(identifier: "ru_RU")), "Украина")
Please add tests for English and Russian geocodes

2021-02-03 15:45 UTC, oleksiikolomiietssnapp approved these changes

2021-02-03 17:48 UTC, svitlana-korostelova approved these changes

2021-02-03 17:48 UTC, merged